title = "Docksal Documentation"
languageCode = "en-us"
theme = "learn"

[params]
  description = "Official Docksal documentation website"
  editURL = "https://github.com/docksal/docksal/edit/develop/docs/content/"

  # Custom CSS => statis/css/theme-docksal.css
  themeVariant = "docksal"

  google_tag_manager = "GTM-58ST6XD"
  google_analytics = "UA-93724315-3"

  version = "v1.16.0"

  [[params.versions]]
  version = "Upcoming"
  branch = "develop"
  url = "https://develop.docs.docksal.io/"

  [[params.versions]]
  version = "v1.16.0"
  branch = "v1.16.0"
  url = "https://docs.docksal.io"

  [[params.versions]]
  version = "v1.15.1"
  branch = "v1.15.1"
  url = "https://v1-15-1.docs.docksal.io"

  [[params.versions]]
  version = "v1.15.0"
  branch = "v1.15.0"
  url = "https://v1-15-0.docs.docksal.io"

  [[params.versions]]
  version = "v1.14.1"
  branch = "v1.14.1"
  url = "https://v1-14-1.docs.docksal.io"

  [[params.versions]]
  version = "v1.14.0"
  branch = "v1.14.0"
  url = "https://v1-14-0.docs.docksal.io"

  [[params.versions]]
  version = "v1.13.3"
  branch = "v1.13.3"
  url = "https://v1-13-3.docs.docksal.io"

  [[params.versions]]
  version = "v1.13.2"
  branch = "v1.13.2"
  url = "https://v1-13-2.docs.docksal.io"

  [[params.versions]]
  version = "v1.13.1"
  branch = "v1.13.1"
  url = "https://v1-13-1.docs.docksal.io"

  [[params.versions]]
  version = "v1.13.0"
  branch = "v1.13.0"
  url = "https://v1-13-0.docs.docksal.io"

  [[params.versions]]
  version = "v1.12.3"
  branch = "v1.12.3"
  url = "https://v1-12-3.docs.docksal.io"

  [[params.versions]]
  version = "v1.12.2"
  branch = "v1.12.2"
  url = "https://v1-12-2.docs.docksal.io"

  [[params.versions]]
  version = "v1.12.1"
  branch = "v1.12.1"
  url = "https://v1-12-1.docs.docksal.io"
  
  [[params.versions]]
  version = "v1.12.0"
  branch = "v1.12.0"
  url = "https://v1-12-0.docs.docksal.io"

  [[params.versions]]
  version = "v1.11.1"
  branch = "v1.11.1"
  url = "https://v1-11-1.docs.docksal.io"

  [[params.versions]]
  version = "v1.11.0"
  branch = "v1.11.0"
  url = "https://v1-11-0.docs.docksal.io"

#  [[params.versions]]
#  version = "v1.10.0"
#  branch = "v1.10.0"
#  url = "https://v1-10-0.docs.docksal.io"

  # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
  # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
  # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
  # add "hide_feedback: true" to the page's front matter.
  [params.ui.feedback]
    enable = true

[outputs]
  home = [ "AMP", "HTML", "JSON", "Sitemap"]

[menu]
  [[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github repo"
  identifier = "ds"
  url = "https://github.com/docksal/docksal"
  weight = 10

  [[menu.shortcuts]]
  name = "<i class='fas fa-list'></i> Versions"
  url = "/versions/"
  weight = 20

  [[menu.shortcuts]]
  name = "<i class='fas fa-bullhorn'></i> Credits"
  url = "/credits/"
  weight = 30

  [[menu.shortcuts]]
  name = "<svg class='gray' viewBox='0 0 16 16' version='1.1' width='16' height='16' aria-hidden='true'><path fill-rule='evenodd' d='M1.5 2.75a.25.25 0 01.25-.25h8.5a.25.25 0 01.25.25v5.5a.25.25 0 01-.25.25h-3.5a.75.75 0 00-.53.22L3.5 11.44V9.25a.75.75 0 00-.75-.75h-1a.25.25 0 01-.25-.25v-5.5zM1.75 1A1.75 1.75 0 000 2.75v5.5C0 9.216.784 10 1.75 10H2v1.543a1.457 1.457 0 002.487 1.03L7.061 10h3.189A1.75 1.75 0 0012 8.25v-5.5A1.75 1.75 0 0010.25 1h-8.5zM14.5 4.75a.25.25 0 00-.25-.25h-.5a.75.75 0 110-1.5h.5c.966 0 1.75.784 1.75 1.75v5.5A1.75 1.75 0 0114.25 12H14v1.543a1.457 1.457 0 01-2.487 1.03L9.22 12.28a.75.75 0 111.06-1.06l2.22 2.22v-2.19a.75.75 0 01.75-.75h1a.25.25 0 00.25-.25v-5.5z'></path></svg> Discussions"
  url = "https://github.com/docksal/docksal/discussions"
  weight = 40
